#!/bin/bash

#PBS -l nodes=1:ppn=5:gpus=1:k80
#PBS -l walltime=24:00:00
#PBS -l mem=16GB
#PBS -N train-paint-data
#PBS -o /work/ls4411/job-output
#PBS -M $lucas.swiniarski@nyu.edu
#PBS -j oe

module purge

cd /work/ls4411/cv_hm3/traffic-sign-detection/

module load torch/gnu/20160623

th main.lua -model custom -cudnn true -batchsize 128 -nEpochs 200

# leave a blank line at the end
